services:

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "8081:80"

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
